{% set name = "atomneb" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomneb-{{ version }}.tar.gz
  sha256: d5366947b1d3d7930eb3df342b13ba695192019e24ccdbe6b2c1cdd5d89f08a9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - astropy >=4.0
    - numpy >=1.17
  run:
    - python >=3.8
    - astropy >=4.0
    - numpy >=1.17

test:
  imports:
    - atomneb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/atomneb/AtomNeb-py
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'atomneb: Python Package for Atomic Data of Ionized Nebulae'
  dev_url: https://github.com/atomneb/AtomNeb-py
  doc_url: https://pypi.python.org/pypi/atomneb

extra:
  recipe-maintainers:
    - danehkar
